.\" Updated for Howdy Next
.TH HOWDY 1 "July 1, 2026" "Howdy Next 3.1.2" "User Commands"
.SH NAME
howdy \- facial authentication for Linux via PAM
.SH SYNOPSIS
.B howdy
[\fB\-U\fR \fIUSER\fR] [\fB\-y\fR] [\fB\-\-plain\fR] [\fB\-h\fR] \fIcommand\fR [\fIarguments\fR...]
.SH DESCRIPTION
Howdy uses your camera and facial recognition as an authentication method
via PAM. Works with login, lock screen, sudo, su, and more.
.PP
This is a modernized fork of the original Howdy project.
.SH COMMANDS
.TP
\fBadd\fR      Add a new face model
.TP
\fBclear\fR    Remove all face models
.TP
\fBconfig\fR   Open config file in editor
.TP
\fBdisable\fR  Enable or disable Howdy
.TP
\fBdownload-models\fR  Download ONNX models from HuggingFace
.TP
\fBlist\fR     List saved face models
.TP
\fBremove\fR   Remove a specific model
.TP
\fBset\fR      Set a config option
.TP
\fBsnapshot\fR  Take a camera snapshot
.TP
\fBtest\fR     Test camera and recognition
.TP
\fBversion\fR  Print version number
.SH OPTIONS
.TP
\fB\-U\fR, \fB\-\-user\fR \fIUSER\fR  Set user account
.TP
\fB\-y\fR     Skip confirmation questions
.TP
\fB\-\-plain\fR  Machine\-friendly output
.TP
\fB\-h\fR, \fB\-\-help\fR  Show help message
.SH FILES
.TP
.I /etc/howdy/config.ini
Main configuration file
.TP
.I /etc/howdy/models/
User face models directory
.SH "SECURITY NOTES"
Howdy is NOT as secure as a password. Photos or similar faces can fool it.
.B Do not use as sole authentication method.
.SH AUTHOR
Originally written by boltgolt. Howdy Next is maintained by nathawat on codeberg.
.SH "SEE ALSO"
.BR pam_howdy (8),
.BR pam (8),
.BR sudo (8)
