name: Test Build
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: codeberg-small
    steps:
      - name: Install required libraries
        run: >
          sudo apt-get update && sudo apt-get install -y
          cmake make build-essential clang-tidy
          libpam0g-dev libinih-dev libevdev-dev libopencv-dev
          libcurl4-openssl-dev nlohmann-json3-dev
          meson ninja-build

      - uses: actions/checkout@v6

      - name: Build
        run: |
          meson setup build
          ninja -C build
          meson test -C build native-capture-smoke-help native-compare-help --print-errorlogs
