name: Test Build
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: codeberg-medium
    container:
      image: codeberg.org/nathawat/howdy-next/ci-1:latest

    steps:
      - uses: actions/checkout@v7

      - name: Build and test
        run: |
          cmake --preset release
          cmake --build --preset release --parallel "$(nproc)"
          ctest --preset release
