from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from types import ModuleType


def _load_paths_module() -> ModuleType:
    try:
        import paths  # type: ignore[import]  # Generated by meson from paths.py.in

        return paths
    except ModuleNotFoundError:
        current = Path(__file__).resolve()
        candidates = [
            current.parent.parent / "paths.py",
            Path("/usr/lib/howdy/paths.py"),
            Path("/usr/lib64/howdy/paths.py"),
            current.parents[3] / "build" / "howdy" / "src" / "paths.py",
        ]

        for candidate in candidates:
            if not candidate.is_file():
                continue

            spec = importlib.util.spec_from_file_location("paths", candidate)
            if spec is None or spec.loader is None:
                continue

            module = importlib.util.module_from_spec(spec)
            sys.modules["paths"] = module
            spec.loader.exec_module(module)
            return module

        raise


paths = _load_paths_module()

YUNET_MODEL = "face_detection_yunet_2023mar_int8bq.onnx"
SFACE_MODEL = "face_recognition_sface_2021dec_int8bq.onnx"


def models_dir_path() -> str:
    return str(paths.models_dir)


def yunet_model_path() -> str:
    return str(Path(models_dir_path()) / YUNET_MODEL)


def sface_model_path() -> str:
    return str(Path(models_dir_path()) / SFACE_MODEL)


def user_model_path(user: str) -> str:
    return str(paths.user_models_dir / f"{user}.dat")


def config_file_path() -> str:
    return str(paths.config_dir / "config.ini")


def snapshots_dir_path() -> str:
    return str(paths.log_path / "snapshots")


def snapshot_path(snapshot: str) -> str:
    return str(Path(snapshots_dir_path()) / snapshot)


def user_models_dir_path() -> str:
    return str(paths.user_models_dir)
