from pathlib import Path

import paths  # type: ignore[import]  # Generated by meson from paths.py.in

YUNET_MODEL = "face_detection_yunet_2023mar_int8bq.onnx"
SFACE_MODEL = "face_recognition_sface_2021dec_int8bq.onnx"


def models_dir_path() -> str:
    return str(paths.models_dir)


def yunet_model_path() -> str:
    return str(Path(models_dir_path()) / YUNET_MODEL)


def sface_model_path() -> str:
    return str(Path(models_dir_path()) / SFACE_MODEL)


def user_model_path(user: str) -> str:
    return str(paths.user_models_dir / f"{user}.dat")


def config_file_path() -> str:
    return str(paths.config_dir / "config.ini")


def snapshots_dir_path() -> str:
    return str(paths.log_path / "snapshots")


def snapshot_path(snapshot: str) -> str:
    return str(Path(snapshots_dir_path()) / snapshot)


def user_models_dir_path() -> str:
    return str(paths.user_models_dir)