function(howdy_set_test_timeouts)
	get_property(HOWDY_DIRECTORY_TESTS DIRECTORY PROPERTY TESTS)
	if(HOWDY_DIRECTORY_TESTS)
		foreach(howdy_test IN LISTS HOWDY_DIRECTORY_TESTS)
			get_test_property(${howdy_test} TIMEOUT howdy_test_timeout)
			if(howdy_test_timeout STREQUAL "NOTFOUND")
				set_tests_properties(${howdy_test} PROPERTIES TIMEOUT 30)
			endif()
		endforeach()
	endif()
endfunction()
